##################################### CYBERPI MODELS ####################################################
[CyberPi_base]
board = esp32dev
monitor_speed = 115200
board_build.partitions = custom_4Mb_full.csv
; Wichtig: Verknüpft den CyberPi-Ordner für interface.cpp und pins_arduino.h
build_src_filter = ${env.build_src_filter} +<../boards/CyberPi>

build_flags =
    ; 1. Zuerst die globalen Flags laden
    ${env.build_flags}
    ${env_4mb.build_flags}
    
    ; 2. Bestehende Definitionen LÖSCHEN (Direkt ohne Leerzeichen nach -U)
    -UILI9341_DRIVER
    -UBRUCE_VERSION
    -UDEVICE_NAME
    
    ; 3. Pfade setzen
    -Iboards/CyberPi
    -Ilib
    -Ilib/HAL/io_expander
    
    ; 4. CyberPi Hardware & Version NEU DEFINIEREN
    -DCYD=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=128
    -DTFT_INVERSION_ON
    
    ; WICHTIG: Dreifache Eskalierung für Strings in GitHub Actions
    -DDEVICE_NAME='\"CyberPi-Bruce\"'
    -DBRUCE_VERSION='\"CyberPi-v1\"'
    
    ; --- RESTLICHE PINS ---
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=27
    -DTFT_RST=33
    -DTFT_BL=26
    -DI2C_SDA=21
    -DI2C_SCL=22
    -DIO_EXPANDER_AW9523=1
    -DIO_EXPANDER_ADDR=0x58
    -DIO_EXP_UP=4
    -DIO_EXP_DOWN=5
    -DIO_EXP_LEFT=6
    -DIO_EXP_RIGHT=7
    -DIO_EXP_SEL=8


; --- Standard Environment für den Build ---
[env:CyberPi]
extends = CyberPi_base
build_flags =
    ${CyberPi_base.build_flags}
    -DSPI_FREQUENCY=40000000

; --- Light Version für M5Launcher Kompatibilität ---
[env:LAUNCHER_CyberPi]
extends = CyberPi_base
board_build.partitions = custom_4Mb.csv
build_flags =
    ${CyberPi_base.build_flags}
    ${env_light.build_flags}
lib_deps =
    ${env_light.lib_deps}
################################# END OF CYBERPI ####################################################
